/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package module_transaksi.view;

import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import module.database.KoneksiDatabase;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author akashaka
 */
public class TransaksiView extends javax.swing.JInternalFrame {

    private Integer maxQTY = 0;
    DefaultTableModel dTB;

    public Integer getMaxQTY() {
        return maxQTY;
    }

    public void setMaxQTY(Integer maxQTY) {
        this.maxQTY = maxQTY;
    }

    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() {
        initComponents();
        jIdtxt.setVisible(false);
        dTB = new DefaultTableModel();
        dTB.addColumn("id barang");
        dTB.addColumn("nama barang");
        dTB.addColumn("harga barang");
        dTB.addColumn("qty beli");
        dTB.addColumn("subtotal");

        transaksiTB.setModel(dTB);
    }

    public JTextField getIdTextField() {
        return jIdtxt;
    }

    public JTextField getNamaTextField() {
        return jNameTxt;
    }

    public JTextField getHargaTextField() {
        return jHbar;
    }

    public JTextField getsubTotal() {
        return jTot;
    }

    public JTextField getjQty() {
        return jQty;
    }

    private void Datatransaksi() {
        DataTransaksiView VDT = new DataTransaksiView(this);
        VDT.setVisible(true);
    }

    Boolean tampil = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jHbar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jQty = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTot = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jIdtxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTotB = new javax.swing.JTextField();
        jKem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        juang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TampiltabelBT = new javax.swing.JButton();
        tabelPN = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transaksiTB = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembeli",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pembeli");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(252, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addContainerGap(60, Short.MAX_VALUE)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Rekap Transaksi");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barang",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Nama Barang");

        jNameTxt.setEditable(false);
        jNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jHbar.setEditable(false);
        jHbar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Harga Barang");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Qty Beli");

        jQty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQtyKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQtyKeyTyped(evt);
            }
        });

        jButton3.setText("Tambah Barang");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTot.setEditable(false);
        jTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotActionPerformed(evt);
            }
        });

        jLabel2.setText("Subtotal");

        jButton4.setText("Pilih barang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(46, 46, 46)
                                                        .addComponent(jNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(75, 75, 75)
                                                        .addComponent(jQty, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jButton4)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(46, 46, 46)
                                                .addComponent(jHbar, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 193, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jTot, javax.swing.GroupLayout.PREFERRED_SIZE, 257,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jButton3)
                                                        .addGap(22, 22, 22)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jHbar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jQty, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTot, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaksi",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Total Belanja");

        jTotB.setEditable(false);
        jTotB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jKem.setEditable(false);
        jKem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Uang Bayar");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Input Data Belanja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        juang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        juang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                juangKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Kembalian");

        TampiltabelBT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TampiltabelBT.setText("Tampil Keranjang");
        TampiltabelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // TampiltabelBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTotB)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel12))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(juang, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jKem, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTotB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(juang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jKem, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addGap(12, 12, 12)));

        transaksiTB.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(transaksiTB);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Data Keranjang Belanja");

        javax.swing.GroupLayout tabelPNLayout = new javax.swing.GroupLayout(tabelPN);
        tabelPN.setLayout(tabelPNLayout);
        tabelPNLayout.setHorizontalGroup(
                tabelPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelPNLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(tabelPNLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel13)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        tabelPNLayout.setVerticalGroup(
                tabelPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelPNLayout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jMenu1.setText("Transaksi");

        jMenuItem2.setText("Data Transaksi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kembali");

        jMenuItem1.setText("Kembali");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(379, 379, 379)
                                                .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tabelPN, javax.swing.GroupLayout.PREFERRED_SIZE, 504,
                                                Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tabelPN, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(58, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jButton2ActionPerformed

    void clearAll() {
        jTotB.setText("");
        juang.setText("");
        clearForm();
        jKem.setText("");
        dTB = new DefaultTableModel();
        dTB.addColumn("id barang");
        dTB.addColumn("nama barang");
        dTB.addColumn("harga barang");
        dTB.addColumn("qty beli");
        dTB.addColumn("subtotal");

        transaksiTB.setModel(dTB);
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    void hitungTotal() {
        int sum = 0;
        for (int i = 0; i < dTB.getRowCount(); i++) {
            Integer curTotal;
            curTotal = Integer.parseInt((String) dTB.getValueAt(i, 4));
            sum += curTotal;
        }
        jTotB.setText("" + sum);
    }

    int getIndexSimmilarItem(String idBarang) {
        for (int i = 0; i < dTB.getRowCount(); i++) {
            if (dTB.getValueAt(i, 0).equals(idBarang)) {
                return i;
            }
        }
        return -1;
    }

    void hitungKembalian() {
        int TotalHarga = 0;
        int TotalBayar = 0;
        if (!jTotB.getText().isEmpty()) {
            TotalHarga = Integer.parseInt((String) jTotB.getText().replace("Rp.", ""));

        }
        if (!juang.getText().isEmpty()) {
            TotalBayar = Integer.parseInt((String) juang.getText());
        }

        int Kembalian = TotalBayar - TotalHarga;
        if (Kembalian < 1) {
            jKem.setText(0 + "");
        } else {
            jKem.setText(Kembalian + "");
        }
    }

    void clearForm() {
        jIdtxt.setText("");
        jNameTxt.setText("");
        jHbar.setText("");
        jTot.setText("");
        jQty.setText("");
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTot.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "qty tidak boleh kosong");
        } else {

            try {
                int indexAdded = getIndexSimmilarItem(jIdtxt.getText());
                boolean isItemAlreadyAdded = indexAdded >= 0;
                if (isItemAlreadyAdded) {
                    int totalAlreadyAdded = Integer.parseInt((String) dTB.getValueAt(indexAdded, 3));
                    int subTotalAlreadyAdded = Integer.parseInt((String) dTB.getValueAt(indexAdded, 4));
                    String total = jTot.getText();
                    String qty = jQty.getText();
                    Integer allTotalQty = totalAlreadyAdded + Integer.parseInt(qty);
                    Integer allSubtotal = Integer.parseInt(total) + subTotalAlreadyAdded;
                    dTB.setValueAt(allTotalQty + "", indexAdded, 3);
                    dTB.setValueAt(allSubtotal + "", indexAdded, 4);
                    hitungTotal();
                    hitungKembalian();
                    clearForm();
                } else {
                    String idBar = jIdtxt.getText();
                    String nameBar = jNameTxt.getText();
                    String harBar = jHbar.getText();
                    String total = jTot.getText();
                    String qty = jQty.getText();
                    Object[] newRow = new Object[5];
                    newRow[0] = idBar;
                    newRow[1] = nameBar;
                    newRow[2] = harBar;
                    newRow[3] = qty;
                    newRow[4] = total;
                    dTB.addRow(newRow);
                    hitungTotal();
                    hitungKembalian();
                    clearForm();

                }

            } catch (Exception e) {
            }
        }
        // dTB.addColumn("id barang");
        // dTB.addColumn("nama barang");
        // dTB.addColumn("harga barang");
        // dTB.addColumn("qty beli");
        // dTB.addColumn("subtotal");
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // INSERT INTO `transaksi` (`id_trans`, `nama_pel`, `tanggal_trans`,
        // `total_belanja`, `kembalian`)
        // VALUES (NULL, 'jksq', CURRENT_TIMESTAMP, '12000', '0');
        // SET @last_id_in_table1 = LAST_INSERT_ID();
        // INSERT INTO `detail_trans` (`id_trans`, `id_barang`, `harga_barang`,
        // `jumlah_belanja`) VALUES
        // (@last_id_in_table1 , '1', '1000', '6'),
        // (@last_id_in_table1 , '2', '1500', '4')
        // INSERT INTO `transaksi` (`id_trans`, `nama_pel`, `tanggal_trans`,
        // `total_belanja`, `kembalian`)
        // VALUES (NULL, 'jksq', CURRENT_TIMESTAMP, '12000', '0');
        if (dTB.getRowCount() > 0 && !jTextField2.getText().isEmpty() && !juang.getText().isEmpty()) {
            String nama_pelanggan = "no name";
            if (!jTextField2.getText().isEmpty()) {
                nama_pelanggan = jTextField2.getText();
            }
            String sql = "INSERT INTO `transaksi` (`id_trans`, `nama_pel`, `tanggal_trans`, `total_belanja`,`uang_bayar`, `kembalian`)"
                    + "VALUES (NULL, '" + nama_pelanggan + "', CURRENT_TIMESTAMP, '" + jTotB.getText() + "', '"
                    + juang.getText() + "','" + jKem.getText() + "');";
            // sql += " SET @last_id_in_table1 = LAST_INSERT_ID();";

            try {
                Statement stmt = KoneksiDatabase.getKoneksi().createStatement();
                long lastInsertedID = stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
                ResultSet rs = stmt.getGeneratedKeys();
                if (rs.next()) {
                    sql = " INSERT INTO `detail_trans` (`id_trans`, `id_barang`, `harga_barang`, `jumlah_belanja`) VALUES ";
                    for (int i = 0; i < dTB.getRowCount(); i++) {
                        String postfix = i == 0 ? "" : ", ";
                        String idBarang = (String) dTB.getValueAt(i, 0);
                        String harBar = (String) dTB.getValueAt(i, 2);
                        String qty = (String) dTB.getValueAt(i, 3);
                        String nSql = "(" + rs.getLong(1) + " , '" + idBarang + "', '" + harBar + "', '" + qty + "')";
                        sql += postfix + nSql;
                    }
                    sql += ";";
                    System.out.println("Last Inserted ID = " + rs.getLong(1));
                    PreparedStatement eksekusi = KoneksiDatabase.getKoneksi().prepareStatement(sql);
                    eksekusi.execute();
                    clearForm();
                    clearAll();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan ke dalam Database");

                }

            } catch (SQLException ex) {
                // Logger.getLogger(ModelPelanggan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Data gagal disimpan ke dalam Database \n" + ex + "\n" + sql);
            }
        } else {
            JOptionPane.showMessageDialog(null, "semua text field wajib diisi");

        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ViewListDataBarang VLDB = new ViewListDataBarang(this);
        VLDB.setVisible(true);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jTotActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTotActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTotActionPerformed

    private void jQtyKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jQtyKeyReleased
        // TODO add your handling code here:
        Integer currentInteger = Integer.parseInt(jQty.getText());
        boolean isItemAlreadyAdded = false;
        int alreadyUsed = 0;
        if (getIndexSimmilarItem(jIdtxt.getText()) >= 0) {
            isItemAlreadyAdded = true;
            alreadyUsed = Integer.parseInt((String) dTB.getValueAt(getIndexSimmilarItem(jIdtxt.getText()), 3));
        }
        Integer max = (maxQTY - alreadyUsed);
        if (max < currentInteger) {
            jQty.setText(max.toString());

        }
        Integer curreInteger = Integer.parseInt(jQty.getText());
        jTot.setText((curreInteger * Integer.parseInt(jHbar.getText())) + "");
    }// GEN-LAST:event_jQtyKeyReleased

    private void jQtyKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jQtyKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }// GEN-LAST:event_jQtyKeyTyped

    private void juangKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_juangKeyReleased
        // TODO add your handling code here:
        hitungKembalian();
    }// GEN-LAST:event_juangKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TampiltabelBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jHbar;
    private javax.swing.JTextField jIdtxt;
    private javax.swing.JTextField jKem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jQty;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTot;
    private javax.swing.JTextField jTotB;
    private javax.swing.JTextField juang;
    private javax.swing.JPanel tabelPN;
    private javax.swing.JTable transaksiTB;
    // End of variables declaration//GEN-END:variables

}
