/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module_transaksi.view;

import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import module.database.KoneksiDatabase;

/**
 *
 * @author akashaka
 */
public class ViewListDataBarang extends javax.swing.JFrame {

    /**
     * Creates new form ViewListDataBarang
     */

    private TransaksiView VTI;
    private DefaultTableModel tabel;
    private String sql = "";

    public ViewListDataBarang(TransaksiView VTI) {
        initComponents();

        this.VTI = VTI;

        tabel = new DefaultTableModel();

        barangTB.setModel(tabel);
        tabel.addColumn("Id Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jenis Barang");
        tabel.addColumn("quantity Barang");
        tabel.addColumn("Ukuran");

        tabel.addColumn("Harga Barang");

    }

    private void tampilDataBarang(String data) {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();

        if (data.equals("")) {
            sql = "SELECT * FROM barang";
        } else {
            sql = "SELECT * FROM barang WHERE nama LIKE '" + data + "%' ";
        }
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                Object[] hasil;
                hasil = new Object[6];
                hasil[0] = res.getString("id_barang");
                hasil[1] = res.getString("nama");
                hasil[2] = res.getString("jenis");
                hasil[3] = res.getString("quantity");
                hasil[5] = res.getString("harga");
                hasil[4] = res.getString("ukuran");
                tabel.addRow(hasil);

            }

        } catch (SQLException ex) {
            Logger.getLogger(ViewListDataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caribarangTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Barang");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cari Nama Barang");

        caribarangTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caribarangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribarangTFActionPerformed(evt);
            }
        });
        caribarangTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caribarangTFKeyPressed(evt);
            }
        });

        barangTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(barangTB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(caribarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 288, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caribarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caribarangTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caribarangTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_caribarangTFActionPerformed

    private void caribarangTFKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_caribarangTFKeyPressed
        // TODO add your handling code here:
        tampilDataBarang(caribarangTF.getText());

    }// GEN-LAST:event_caribarangTFKeyPressed

    private void barangTBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barangTBMouseClicked
        // TODO add your handling code here:
        int ambilrow = barangTB.getSelectedRow();
        VTI.getIdTextField().setText(barangTB.getValueAt(ambilrow,0).toString());
        VTI.getNamaTextField().setText(barangTB.getValueAt(ambilrow, 1).toString());
        VTI.getHargaTextField().setText(barangTB.getValueAt(ambilrow, 5).toString());
        VTI.setMaxQTY(Integer.parseInt(barangTB.getValueAt(ambilrow, 3).toString()));

        VTI.getjQty().requestFocus();

        this.dispose();
    }// GEN-LAST:event_barangTBMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable barangTB;
    private javax.swing.JTextField caribarangTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
